logging-to-file = true        # enables logging of every patch process to a seperate file
enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app
build-mindetach-module = true

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

[YouTube]
enabled = false
build-mode = "apk"                                                   # 'both', 'apk' or 'module'
excluded-patches = ""                                                 # space-seperated patches to exclude (multiline strings are not supported)
included-patches = ""                                                 # space-seperated patches to include (non-excluded patches are included by default)
version = "18.33.35"                                                      # 'auto', 'latest', 'beta' or a custom one like '17.40.41'
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YouTube-Extended-New-devices]
app-name = "YouTube"
patches-source = "vuong2023/testpatch"
integrations-source = "vuong2023/inter"
rv-brand = "ReVanced Extended"
build-mode = "module"
excluded-patches = "custom-branding-name custom-branding-youtube-name custom-branding-icon-mmt custom-branding-icon-revancify-red custom-branding-icon-revancify-blue"
included-patches = "materialyou disable-landscape-mode hide-double-tap-overlay-filter enable-debug-logging"
version = "18.36.39"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YouTube-Extended-Old-Devices]
enabled = false
app-name = "YouTube"
patches-source = "kitadai31/revanced-patches-android6-7"
integrations-source = "kitadai31/revanced-integrations"
rv-brand = "ReVanced Extended"
build-mode = "both"
excluded-patches = ""
included-patches = ""

apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
enabled = false
build-mode = "both"
excluded-patches = "hide-upgrade-button"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "both"                                                     # both arm64-v8a and arm-v7a

[Music-Extended]
enabled = false
app-name = "Music"
patches-source = "YT-Advanced/testpatch"
integrations-source = "YT-Advanced/testinte"
cli-source = "YT-Advanced/revanced-cli"
rv-brand = "Music"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"

[Twitter]
enabled = false
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Twitch]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Reddit]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Messenger]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"

[Spotify]
enabled = false
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"
apkmirror-arch = "arm64-v8a"

[Backdrops]
enabled = false
uptodown-dlurl = "https://backdrops.en.uptodown.com/android"

[WarnWetter]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[IconPackStudio]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"
apkmirror-arch = "arm64-v8a"

[Tasker]
enabled = false
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"

[Photomath]
enabled = false
apkmonk-dlurl = "https://www.apkmonk.com/app/com.microblink.photomath/"
